name: Download CSV and Upload to Sharepoint

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install boto3 requests

      - name: Run script
        run: python main.py
